# -*- coding: utf-8 -*-
"""textchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lqm9r4OZ5iuUZx4qZ-FtfnOGEoOL1rZF
"""

# ✅ STEP 1: Install dependencies
!pip install -q -U google-generativeai
!pip install -q python-dotenv

# ✅ Step 2: Configure your Gemini API key directly
import os
import google.generativeai as genai

# ⚠️ Replace YOUR_API_KEY_HERE with your real Gemini API key from Google AI Studio:
#     https://aistudio.google.com/app/apikey
os.environ["GEMINI_API_KEY"] = "AIzaSyAwwvKCGfiNh9NVmq4g7z7NjvjEfGCP-ns"

# Configure the Gemini client
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

print("✅ Gemini API key configured successfully!")

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

# ✅ STEP 3: Initialize the correct model
# Use the latest supported text-capable model (most stable and powerful)
model = genai.GenerativeModel("gemini-2.5-pro")

# ✅ STEP 4: Define the contextual system prompt (prompt engineering)
HIREMATIC_CONTEXT = """
You are HireMatic AI Assistant — a smart, professional chatbot for the AI-powered recruitment system 'HireMatic'.

HireMatic automates recruitment through AI, Machine Learning, NLP, and Computer Vision.

System Overview:
1. Admin Dashboard — manage users, roles, and reports.
2. Job Generation — create detailed job descriptions automatically.
3. Candidate Portal — allow candidates to register, apply, and track applications.
4. Smart Resume Parsing & Scoring — extract key info and rank candidates.
5. Interview Scheduling — automate interview setup and communication.
6. Virtual Interviewer — conduct adaptive, real-time interviews.
7. Evaluation & Fairness System — detect bias and analyze engagement.
8. Automated Interview Reporting — generate insights and ranking reports.

Your objectives:
- Always respond clearly, accurately, and professionally.
- Keep answers relevant to HireMatic’s modules and functionalities.
- Adjust tone and content depending on user type (Admin, HR, or Candidate).
- If someone asks about something unrelated to HireMatic, politely redirect.
"""

# ✅ STEP 5: Define chatbot function
def hirematic_chat(user_query, role="general"):
    role_contexts = {
        "hr": "You are assisting an HR professional managing recruitment in HireMatic.",
        "candidate": "You are guiding a job candidate using the HireMatic portal.",
        "admin": "You are helping an administrator configure and monitor HireMatic.",
        "general": "You are providing general help about HireMatic."
    }

    full_prompt = f"""
{HIREMATIC_CONTEXT}

{role_contexts.get(role, role_contexts['general'])}

User Query: {user_query}

Respond in a friendly, professional tone.
"""
    response = model.generate_content(full_prompt)
    return response.text

# ✅ STEP 6: Test the chatbot interactively
while True:
    query = input("You: ")
    if query.lower() in ["exit", "quit", "bye"]:
        print("HireMatic Bot: Goodbye! 👋")
        break
    answer = hirematic_chat(query)
    print("HireMatic Bot:", answer, "\n")